//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boletim
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUNO_ATIVIDADE
    {
        public int COD_ALUNO { get; set; }
        public int COD_ATIVIDADE { get; set; }
        public Nullable<double> NOTA { get; set; }
    
        public virtual ALUNO ALUNO { get; set; }
        public virtual ATIVIDADE ATIVIDADE { get; set; }
    }
}
